### ISSUE TITLE
kite-mini can't recognize multiple chrome instances

### ISSUE THREAD

**Issue by stardiviner** [tungd/kite-mini.el#9]
I got the following error when eval with `[C-x C-e]`

```
websocket-debug: Wrong type argument: arrayp, nil
```

My emacs version: 24.5.1
kite-mini version: `20150811.1129` from MELPA.

**Comment by tungd** [comment]
Hi,
I can't seems to figure out the issue yet. What does the line of code causing the error? Also can you try turn on debug on error (`M-x toggle-debug-on-error`) and give me the stacktrace?

Thanks

**Comment by stardiviner** [comment]
Sorry for this, This is caused by my wrong usage. I started two chrome instance. That's why `kite-mini-connect` wrong. so evaluation failed.

**Comment by stardiviner** [comment]
BTW, can kite-mini support for multiple chrome instance which only one instance is started by `--remote-debug-port=9222` ?

**Comment by tungd** [comment]
That's weird. There is always only one processes listening at port 9222 and kite-mini only connect to that. I will try starting two Chrome instances and see.

**Comment by stardiviner** [comment]
Is there any progress on this?

**Comment by tungd** [comment]
Hi, 

I can't seem to open two Chrome instances, when I run the `chromium`/`chrome` command it opens a new window (with the same existing process pool). Maybe that's what caused your issue, the second Chrome instance started with the debug flag, but it only reuse the processes (which started without the debug flag).

Make sure you started the very first Chrome instance with `--remote-debug-port=9222`. You can try kill all Chrome processes, start one with the debug flag first and then start one normally.

Anyways, if you tried and the problem still occur, send me the stacktrace could help.

**Comment by stardiviner** [comment]
So no workaround except start chrome very first.
Do I need to keep this issue open?

**Comment by tungd** [comment]
Correct, this issue is more about how Chrome works, there's nothing we can do. I will close the issue, thanks for participating.

Have a nice day :+1:
